// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_SU9mRsly0",
    "aws_user_pools_web_client_id": "5816futqhcdliq42j14i21jhde",
    "oauth": {}
};


export default awsmobile;
